//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc2stok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblmusteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblmusteri()
        {
            this.tblsatıis = new HashSet<tblsatıis>();
        }
    
        public int musteriid { get; set; }
        [Required(ErrorMessage ="Bu alanı boş geçemezsiniz...!")]
        [StringLength(50,ErrorMessage ="50 karakterden fazla giriş yapamazsnız...!")]
        public string musteriad { get; set; }
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz...!")]
        [StringLength(50, ErrorMessage = "50 karakterden fazla giriş yapamazsnız...!")]
        public string musterisoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatıis> tblsatıis { get; set; }
    }
}
