//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc2stok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsatıis
    {
        public int satısid { get; set; }
        public Nullable<int> urunid { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<byte> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        public virtual tblmusteri tblmusteri { get; set; }
        public virtual tblurunler tblurunler { get; set; }
    }
}
