//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc2stok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblurunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblurunler()
        {
            this.tblsatıis = new HashSet<tblsatıis>();
        }
    
        public int Urunid { get; set; }
        [Required(ErrorMessage ="bu alanı boş geçemezsiniz...!")]
        public string urunad { get; set; }
        [Required(ErrorMessage = "bu alanı boş geçemezsiniz...!")]
        public string Urunmarka { get; set; }
        public Nullable<short> urunkategori { get; set; }
        [Required(ErrorMessage = "bu alanı boş geçemezsiniz...!")]
        public Nullable<decimal> urunfiyat { get; set; }
        public Nullable<byte> stok { get; set; }
    
        public virtual tblkategori tblkategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatıis> tblsatıis { get; set; }
    }
}
